### ISSUE TITLE
deals.find() doesn't return the whole deal

### ISSUE THREAD

**Issue by lee-40square** [yurypaleev/BaseCRM#10]
If I do `https://api.getbase.com/v2/deals` I get the full deal. But if I do `client.deals.find()` I get this. Note the missing `organization_id` (and other details).

```
{
    name: 'Some Deal Name',
    hot: false,
    currency: 'USD',
    loss_reason_id: null,
    source_id: null,
    last_stage_change_at: '2017-02-22T18:37:52Z',
    owner_id: 000000,
    value: 2950,
    stage_id: 000000,
    contact_id: 000000,
    estimated_close_date: null,
    customized_win_likelihood: null,
    custom_fields: {},
    tags: [] 
}
```

**Comment by yurypaleev** [comment]
For deals `['id', 'creator_id', 'last_stage_change_by_id', 'last_activity_at', 'dropbox_email', 'organization_id', 'created_at', 'updated_at']` it's read only params, and it's not displayed in the console, but it's there.

**Comment by lee-40square** [comment]
Thanks for the help. Got it working.
