### ISSUE TITLE
Unhandled rejection RequestError: Error: Invalid URI "/v2/contacts

### ISSUE THREAD

**Issue by karlito40** [yurypaleev/BaseCRM#5]
This old closed error is still happening.
<pre>var BaseCRM = require('basecrm');
var accessToken = '4b3576b78cb46f3453e8be18355f42a9daa8fcfce08c1f85f2ab68b4abf6d44f';

var client = new BaseCRM.Client({
    accessToken: accessToken
});

var resource = client.contacts;
resource.create({
    first_name: 'Foo',
    last_name: 'Foo'
});</pre>

With the same accessToken i'm able to curl properly into Base.

This is working fine.

`curl -v -X POST https://api.getbase.com/v2/contacts -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer accessToken" -d '{
  "data": {
      "name": "Mark Johnson",
      "first_name": "Mark",
      "last_name": "Johnson"
  }'`

I will investigate the issue.

**Comment by yurypaleev** [comment]
You should specify the required field "name".
See [API](https://developers.getbase.com/docs/rest/reference/contacts).

```javascript
client.contacts.create({
    name: "Mark Johnson",
    first_name: "Mark",
    last_name: "Johnson"
});
```
