### ISSUE TITLE
Cannot get a single Deal

### ISSUE THREAD

**Issue by khadlock** [yurypaleev/BaseCRM#6]
I'm retrieving a full list of BaseCRM deals, but I've tried everything to get a single deal and it doesn't seem to work. Can you please help?

base.deals.find(id).then(function(deal) {}); 
base.deals.find({"id":id}).then(function(deal) {}); 
base.deals.find([id]).then(function(deal) {}); 
base.deals.find(Number(id)).then(function(deal) {});

**Comment by yurypaleev** [comment]
Use code like this, for example:
```javascript
base.deals.find(12345678).then(function(deal) {
  console.log(deal);
});
```
