### ISSUE TITLE
How to handle pagination

### ISSUE THREAD

**Issue by eoleary** [yurypaleev/BaseCRM#8]
Do you have a way to deal with the pagination of results?  I'd like to look through all my contact to normalize data but I can't find a way to specify the page I want.

https://developers.getbase.com/docs/rest/articles/requests

Thanks and thank you for creating this project,

Eddie

**Comment by eglas** [comment]
You can. 

You need to specify a per page results limit and use the page parameter to get to the desired page: 


```javascript
client.contacts.find({
    'per_page': 100,
    'page': 2
})
```

That would bring 100 results from page 2.

**Comment by eoleary** [comment]
Thank you!
